#!/usr/bin/env python3
"""Local TLS comparison helpers for check_local_tor.py --traffic-report.

Capture only loopback traffic generated by the controlled test. Reports contain
TLS record lengths/timing and ClientHello structure, never application payloads,
TLS randoms, session IDs, public keys, or server names. This is a distinguisher
check, not an anonymity test or a claim of browser fingerprint equivalence.
"""
import collections
import json
import socket
import struct
import subprocess
import threading
import time


def u16(data):
    return struct.unpack("!H", data)[0]


def vector(data, width):
    if len(data) < width:
        raise ValueError("truncated TLS vector length")
    length = int.from_bytes(data[:width], "big")
    if len(data) < width + length:
        raise ValueError("truncated TLS vector")
    return data[width:width + length], data[width + length:]


def words(data):
    if len(data) % 2:
        raise ValueError("odd TLS word vector")
    return [u16(data[i:i + 2]) for i in range(0, len(data), 2)]


def client_hello(data):
    if len(data) < 34:
        raise ValueError("truncated ClientHello")
    result = {"legacy_version": u16(data[:2])}
    session, data = vector(data[34:], 1)  # discard random/session ID
    result["session_id_length"] = len(session)
    suites, data = vector(data, 2)
    result["cipher_suites"] = words(suites)
    compression, data = vector(data, 1)
    result["compression_methods"] = list(compression)
    extensions, data = vector(data, 2) if data else (b"", b"")
    if data:
        raise ValueError("extra ClientHello bytes")
    result["extensions"] = []
    result["server_name_present"] = False
    result["key_shares"] = []
    while extensions:
        if len(extensions) < 4:
            raise ValueError("truncated extension")
        kind = u16(extensions[:2])
        body, extensions = vector(extensions[2:], 2)
        if kind in result["extensions"]:
            raise ValueError("duplicate ClientHello extension")
        result["extensions"].append(kind)
        if kind in (10, 13, 43):
            values, rest = vector(body, 1 if kind == 43 else 2)
            if rest:
                raise ValueError("extra extension bytes")
            result[{10: "supported_groups", 13: "signature_algorithms", 43: "supported_versions"}[kind]] = words(values)
        if kind == 51:
            shares, rest = vector(body, 2)
            if rest:
                raise ValueError("extra key share bytes")
            while shares:
                if len(shares) < 4:
                    raise ValueError("truncated key share")
                group = u16(shares[:2])
                key, shares = vector(shares[2:], 2)
                result["key_shares"].append({"group": group, "length": len(key)})
        if kind == 0:
            names, rest = vector(body, 2)
            if rest:
                raise ValueError("extra SNI bytes")
            if not names or names[0] != 0:
                raise ValueError("invalid SNI name type")
            name, rest = vector(names[1:], 2)
            if rest or not name:
                raise ValueError("invalid SNI name")
            result["server_name_present"] = True
            result["server_name_length"] = len(name)
            # Record a shape predicate, never the name itself.
            label = name[4:-4]
            result["server_name_tor_shape"] = (name.startswith(b"www.") and
                name.endswith(b".com") and 4 <= len(label) <= 25 and
                all(c in b"abcdefghijklmnopqrstuvwxyz234567" for c in label))
    return result


class RecordTrace:
    def __init__(self):
        self.buffer = bytearray()
        self.handshake = bytearray()
        self.records = []
        self.hello = None
        self.total_bytes = 0
        self.started = time.monotonic()

    def feed(self, data):
        self.total_bytes += len(data)
        # The local check stops quickly; independently bound retained metadata.
        if len(self.records) >= 256:
            return
        self.buffer.extend(data)
        while len(self.buffer) >= 5:
            kind, version, length = struct.unpack("!BHH", self.buffer[:5])
            if length > 18432:
                raise ValueError("oversized TLS record")
            if len(self.buffer) < length + 5:
                return
            body = bytes(self.buffer[5:5 + length])
            del self.buffer[:5 + length]
            self.records.append({"type": kind, "version": version, "length": length,
                                 "at_ms": round((time.monotonic() - self.started) * 1000, 3)})
            if kind == 22 and self.hello is None:
                self.handshake.extend(body)
                if len(self.handshake) > 65536:
                    raise ValueError("oversized handshake")
                if len(self.handshake) >= 4:
                    size = int.from_bytes(self.handshake[1:4], "big")
                    if self.handshake[0] != 1:
                        self.handshake.clear()
                    elif len(self.handshake) >= size + 4:
                        self.hello = client_hello(bytes(self.handshake[4:size + 4]))
                        self.handshake.clear()
            if len(self.records) >= 256:
                self.buffer.clear()
                return

    def report(self):
        return {"client_hello": self.hello, "total_bytes": self.total_bytes,
                "records": self.records, "record_limit": 256}


class Tap:
    """A single controlled loopback connection; never an open network proxy."""
    def __init__(self, relay_port):
        self.listener = socket.socket()
        self.listener.bind(("127.0.0.1", 0))
        self.listener.listen(1)
        self.listener.settimeout(8)
        self.port = self.listener.getsockname()[1]
        self.relay_port = relay_port
        self.outbound, self.inbound = RecordTrace(), RecordTrace()
        self.error = None
        self.sockets = []
        self.thread = threading.Thread(target=self.run)
        self.thread.start()

    def run(self):
        try:
            client, _ = self.listener.accept()
            relay = socket.create_connection(("127.0.0.1", self.relay_port), timeout=5)
            client.settimeout(5)
            relay.settimeout(5)
            self.sockets = [client, relay]
            def pump(source, target, trace):
                try:
                    while data := source.recv(16384):
                        trace.feed(data)
                        target.sendall(data)
                except (ConnectionError, OSError):
                    pass  # shutdown/timeout after the bounded observation
                except ValueError as error:
                    self.error = str(error)
                finally:
                    try:
                        target.shutdown(socket.SHUT_WR)
                    except OSError:
                        pass
            backward = threading.Thread(target=pump, args=(relay, client, self.inbound))
            backward.start()
            pump(client, relay, self.outbound)
            backward.join(6)
        except OSError as error:
            self.error = str(error)
        finally:
            for sock in self.sockets:
                sock.close()
            self.listener.close()

    def finish(self):
        self.thread.join(12)
        if self.thread.is_alive():
            raise RuntimeError("local TLS tap did not stop")
        if self.error or self.outbound.hello is None:
            raise RuntimeError(self.error or "no complete ClientHello captured")
        return {"outbound": self.outbound.report(), "inbound": self.inbound.report()}


def capture_pair(tor, veil, root, relay_port, rsa_pin, ed_pin):
    tap = Tap(relay_port)
    subprocess.run([str(veil), "channel-check", "-address", f"127.0.0.1:{tap.port}",
                    "-rsa", rsa_pin, "-ed25519", ed_pin, "-timeout", "5s"],
                   check=True, capture_output=True, timeout=8)
    native = tap.finish()
    tap = Tap(relay_port)
    data = root / "fingerprint-client"
    data.mkdir(mode=0o700)
    config = root / "fingerprint-client.torrc"
    config.write_text("\n".join([
        f'DataDirectory "{data}"', "ClientOnly 1", "SocksPort 0", "UseBridges 1",
        f"Bridge 127.0.0.1:{tap.port} {rsa_pin}", "UseDefaultFallbackDirs 0",
        "DirAuthority local orport=1 v3ident=" + "A" * 40 + " 127.0.0.1:1 " + "B" * 40,
        "TestingTorNetwork 1", "Log notice stdout",
    ]) + "\n")
    with (root / "fingerprint-client.log").open("w") as log:
        proc = subprocess.Popen([str(tor), "--defaults-torrc", "/dev/null", "-f", str(config)], stdout=log, stderr=subprocess.STDOUT)
        try:
            # A fixed, bounded observation; no destination application traffic.
            time.sleep(4)
        finally:
            proc.terminate()
            try:
                proc.wait(timeout=3)
            except subprocess.TimeoutExpired:
                proc.kill()
                proc.wait(timeout=3)
    reference = tap.finish()
    return {"veil": native, "c_tor": reference}


def summarize(pairs):
    """Separate stable structural fields from per-connection random lengths."""
    summary = {}
    for implementation in ("veil", "c_tor"):
        hellos = [pair[implementation]["outbound"]["client_hello"] for pair in pairs]
        fields = sorted(set().union(*(h.keys() for h in hellos)))
        stable, variable = {}, {}
        for key in fields:
            counts = collections.Counter(json.dumps(h.get(key), sort_keys=True) for h in hellos)
            if len(counts) == 1:
                stable[key] = hellos[0].get(key)
            else:
                variable[key] = [{"value": json.loads(value), "count": count}
                                 for value, count in sorted(counts.items())]
        sizes = collections.Counter(pair[implementation]["outbound"]["records"][0]["length"]
                                    for pair in pairs)
        summary[implementation] = {"stable_fields": stable, "variable_fields": variable,
            "first_record_lengths": [{"bytes": size, "count": count} for size, count in sorted(sizes.items())]}
    a,b = (summary[name]["stable_fields"] for name in ("veil", "c_tor"))
    # Length samples are distribution observations, never a structural verdict.
    fields = (a.keys() & b.keys()) - {"server_name_length"}
    differences = {key: {"veil": a[key], "c_tor": b[key]} for key in sorted(fields) if a[key] != b[key]}
    summary["stable_differences"] = differences
    summary["sample_count"] = len(pairs)
    return summary


def compare(tor, veil, root, relay_port, rsa_pin, ed_pin, output, samples=5):
    if not 1 <= samples <= 20:
        raise ValueError("traffic samples must be between 1 and 20")
    pairs = []
    for index in range(samples):
        sample_root = root / f"traffic-sample-{index}"
        sample_root.mkdir(mode=0o700)
        pairs.append(capture_pair(tor, veil, sample_root, relay_port, rsa_pin, ed_pin))
    summary = summarize(pairs)
    tor_build_info = subprocess.check_output([str(tor), "--version"], text=True).splitlines()
    report = {"schema": 2, "scope": "controlled loopback TLS handshake; Veil channel-check vs C Tor bridge client",
              "tor_version": tor_build_info[0], "tor_build_info": tor_build_info,
              "summary": summary, "samples": pairs,
              "limitations": ["Stable means unchanged in these samples, not a population-wide conclusion.",
                              "No statistical indistinguishability verdict is produced from this sample count.",
                              "Different post-handshake lifetimes/workloads: record totals and timings are not parity metrics.",
                              "No browser, application traffic, public network, packet segmentation or anonymity evaluation.",
                              "ClientHello structural equality would not establish indistinguishability."]}
    output.write_text(json.dumps(report, indent=2) + "\n")
    return {"report": str(output), "samples": samples,
            "stable_differing_fields": list(summary["stable_differences"]),
            "variable_fields": {name: list(summary[name]["variable_fields"]) for name in ("veil", "c_tor")}}
